### PR TITLE
make multi lang

### PR DESCRIPTION
**Pull request by hoangtrungthong**
## Related Tickets:
- [#44076](https://edu-redmine.sun-asterisk.vn/issues/44076)

## WHAT this PR does?
make multi lang

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Comment by hoangtrungthong** [comment]
ready

**Comment by hoangtrungthong** [comment]
ready

**Review by ghost — COMMENTED** [review]
Viết cho m cái mô tả và gắn ticket nha

**Comment by hoangtrungthong** [comment]
ready

**Pull request merged**
